version: '3'

services:
  web:
    image: python:3.5
    command:
      - /bin/sh
    environment:
        DATABASE_URL: postgresql://postgres@127.0.0.1:5432/millenium
    volumes:
      - ./postgres-data:/opt/postgresql/data
      - ${PWD}/project:/home/docker/
    working_dir: /home/docker/
    ports:
      - "8000:8000"
